### ISSUE TITLE
Add a licence to this repo

### ISSUE THREAD

**Issue by Binnette** [caffeinewriter/twitch-search#11]
Hi @caffeinewriter, first of all : THANK YOU ❤️ 

Your app is way more than useful to me 👍 It is simple and efficient. It does the job very well.
Ok, there are minor bugs like the pagination (page number is not displayed & button "Next" is displayed even when there are no more results) but it is working very nicely!

Can you please choose a license (MIT?) for your source code? And add the corresponding LICENSE file?

Have a nice day, Merry Christmas & again TY for this app.

PS : I definitively need to check your other apps 👍 Any advice on which one of your apps I may have to give a try?

**Comment by caffeinewriter** [comment]
Hey @Binnette, thanks so much for the kind words. I apologize it took me so long to get back to you. SearchTwitch is now licensed under MIT. I feel simple and permissive is the best way forward for SearchTwitch. 😃 

As far as the pagination displaying "Next" when no further streams are available, I believe that's an unavoidable issue with the Twitch API, where they offer a number of streams that doesn't necessarily match up with the actual number of available streams in the API. One potential workaround I considered is doing a one-page lookahead, but due to the ephemeral nature of streams, and not providing a cached search, it's a bit of a challenging problem. I may work on a backend for this app at some point, which could provide lookahead and caching, but at present, it's definitely tricky, and I welcome any suggestions or PRs!

At present, I don't have much else in the way of actively developed apps, but I do have some plans for Twitch Extensions in the coming months! If you're interested, I may look at putting together some small way to stay up to date, though I do have a small project listing at my [personal website](https://brandonanzaldi.com). Although I've mostly been focused on my day job nowadays, and haven't done nearly as much hobby programming as I'd like to.

Thanks again!
